services:
  app:
    container_name: app
    build: app/
    ports:
      - 80:80
  db:
    container_name: database
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./app/table.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - MARIADB_ROOT_PASSWORD=root
